python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 1024

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 512

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 256

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 128

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 64

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 32

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 16

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 8

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 4

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 32 --lr 1e-3 --device 1 --model vgg16_bn --task_selection genre,artist_name,style,media,century --exp_name all_aux --feature_dim 2
