python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 16 --lr 1e-3 --device 0 --feature_dim 512 --model vgg16_bn --task_selection artist_name,genre,style --exp_name artist_genre_style

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 16 --lr 1e-3 --device 0 --feature_dim 512 --model vgg16_bn --task_selection artist_name,genre,style,media,century --exp_name artist_genre_style_media_century

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 16 --lr 1e-3 --device 0 --feature_dim 512 --model vgg16_bn --task_selection artist_name --exp_name artist

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 16 --lr 1e-3 --device 0 --feature_dim 512 --model vgg16_bn --task_selection genre --exp_name genre

python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 16 --lr 1e-3 --device 0 --feature_dim 512 --model vgg16_bn --task_selection style --exp_name style

#python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 64 --lr 1e-3 --device 0 --feature_dim 512 --model mobilenet_v2 --task_selection artist_name,genre --exp_name artist_genre

#python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 64 --lr 1e-3 --device 0 --feature_dim 512 --model mobilenet_v2 --task_selection artist_name,style --exp_name artist_style

#python train_multitask.py --val_file wikiart_datasets/info_elgammal_subset_val.hdf5 --train_file wikiart_datasets/info_elgammal_subset_train.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --epochs 100 --batch_size 64 --lr 1e-3 --device 0 --feature_dim 512 --model mobilenet_v2 --task_selection genre,style --exp_name genre_style

