python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name artist --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-15-14-56_NarrowNet512_MobileNetV2_artist_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name genre --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-15-20-34_NarrowNet512_MobileNetV2_genre_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name style --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-16-06-06_NarrowNet512_MobileNetV2_style_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name artist_genre --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-16-09-38_NarrowNet512_MobileNetV2_artist_genre_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name artist_style --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-16-14-42_NarrowNet512_MobileNetV2_artist_style_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name genre_style --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-16-19-48_NarrowNet512_MobileNetV2_genre_style_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name artist_genre_style --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-17-01-13_NarrowNet512_MobileNetV2_artist_genre_style_model_best_mean_acc.pth.tar

python get_feature.py --info_file wikiart_datasets/info_elgammal_subset_test.hdf5 --im_path /export/home/kschwarz/Documents/Data/Wikiart_Elgammal/resize_224 --stat_file wikiart_datasets/info_elgammal_subset_train_mean_std.pkl --batch_size 16 --device 0 --feature_dim 512 --output_dir ../evaluation/pretrained_features --model mobilenet_v2 --exp_name artist_genre_style_media_century --weight_file /export/home/kschwarz/Documents/Masters/WebInterface/MapNetCode/pretraining/models/eval_mtl/11-17-10-47_NarrowNet512_MobileNetV2_artist_genre_style_media_century_model_best_mean_acc.pth.tar

